/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author LENOVO
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        LbBatik1 = new javax.swing.JLabel();
        LbBatik2 = new javax.swing.JLabel();
        LbBatik3 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        BtnBatik1 = new javax.swing.JButton();
        BtnBatik2 = new javax.swing.JButton();
        BtnBatik3 = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        imagePanel.setLayout(new java.awt.CardLayout());

        LbBatik1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbBatik1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/batik-1.jpg"))); // NOI18N
        LbBatik1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbBatik1.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(LbBatik1, "0");

        LbBatik2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbBatik2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/batik-2.jpg"))); // NOI18N
        LbBatik2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbBatik2, "1");

        LbBatik3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbBatik3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/batik-3.jpg"))); // NOI18N
        LbBatik3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbBatik3, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        BtnBatik1.setText("Batik1");
        BtnBatik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatik1ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnBatik1);

        BtnBatik2.setText("Batik2");
        BtnBatik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatik2ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnBatik2);

        BtnBatik3.setText("Batik3");
        BtnBatik3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatik3ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnBatik3);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBatik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatik2ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_BtnBatik2ActionPerformed

    private void BtnBatik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatik1ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"0");
    }//GEN-LAST:event_BtnBatik1ActionPerformed

    private void BtnBatik3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatik3ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_BtnBatik3ActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatik1;
    private javax.swing.JButton BtnBatik2;
    private javax.swing.JButton BtnBatik3;
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel LbBatik1;
    private javax.swing.JLabel LbBatik2;
    private javax.swing.JLabel LbBatik3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    // End of variables declaration//GEN-END:variables
}
